
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package pascal.compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 13;
  public static final int RIGHT_BRACKET = 29;
  public static final int CHAR = 51;
  public static final int CONST = 8;
  public static final int EQUALS = 42;
  public static final int DEVIDE = 39;
  public static final int LEFT_KEY = 30;
  public static final int ENTERO = 56;
  public static final int NOT_EQUAL = 43;
  public static final int INTEGER = 52;
  public static final int PRODUCT = 40;
  public static final int ARRAY = 7;
  public static final int MINUS = 38;
  public static final int FOR = 12;
  public static final int GREATER_THAN = 44;
  public static final int NOT = 16;
  public static final int SEMICOLON = 32;
  public static final int AND = 6;
  public static final int RECORD = 20;
  public static final int TYPE = 23;
  public static final int NIL = 15;
  public static final int OR = 18;
  public static final int DIV = 9;
  public static final int BEGIN = 3;
  public static final int WRITE_LN = 4;
  public static final int LESS_EQUAL = 47;
  public static final int PLUS = 37;
  public static final int GREATER_EQUALS = 46;
  public static final int IF = 14;
  public static final int ID = 55;
  public static final int DOT = 35;
  public static final int OF = 17;
  public static final int BOOLEAN = 48;
  public static final int EOF = 0;
  public static final int INT_CONST = 54;
  public static final int TRUE = 49;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int COMA = 34;
  public static final int MOD = 41;
  public static final int RIGHT_PAR = 27;
  public static final int COLON = 33;
  public static final int CHAR_CONS = 53;
  public static final int ELSE = 11;
  public static final int TO = 22;
  public static final int WHILE = 25;
  public static final int THEN = 21;
  public static final int ASIGN = 36;
  public static final int END = 5;
  public static final int RIGHT_KEY = 31;
  public static final int FALSE = 50;
  public static final int LEFT_PAR = 26;
  public static final int LESS_THAN = 45;
  public static final int LEFT_BRACKET = 28;
  public static final int VAR = 24;
  public static final int PROCEDURE = 19;
  public static final int DO = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "BEGIN",
  "WRITE_LN",
  "END",
  "AND",
  "ARRAY",
  "CONST",
  "DIV",
  "DO",
  "ELSE",
  "FOR",
  "FUNCTION",
  "IF",
  "NIL",
  "NOT",
  "OF",
  "OR",
  "PROCEDURE",
  "RECORD",
  "THEN",
  "TO",
  "TYPE",
  "VAR",
  "WHILE",
  "LEFT_PAR",
  "RIGHT_PAR",
  "LEFT_BRACKET",
  "RIGHT_BRACKET",
  "LEFT_KEY",
  "RIGHT_KEY",
  "SEMICOLON",
  "COLON",
  "COMA",
  "DOT",
  "ASIGN",
  "PLUS",
  "MINUS",
  "DEVIDE",
  "PRODUCT",
  "MOD",
  "EQUALS",
  "NOT_EQUAL",
  "GREATER_THAN",
  "LESS_THAN",
  "GREATER_EQUALS",
  "LESS_EQUAL",
  "BOOLEAN",
  "TRUE",
  "FALSE",
  "CHAR",
  "INTEGER",
  "CHAR_CONS",
  "INT_CONST",
  "ID",
  "ENTERO"
  };
}

