
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 26 20:57:16 CST 2017
//----------------------------------------------------

package pascal.compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 37;
  public static final int STRING_LITERAL = 70;
  public static final int FUNCTION = 12;
  public static final int RIGHT_BRACKET = 29;
  public static final int CHAR = 59;
  public static final int PACKED = 54;
  public static final int WITH = 48;
  public static final int CONST = 7;
  public static final int EQUALS = 41;
  public static final int LEFT_KEY = 60;
  public static final int CASE = 55;
  public static final int NOT_EQUAL = 42;
  public static final int XOR = 39;
  public static final int INTEGER = 47;
  public static final int REPEAT = 57;
  public static final int FORWARD = 56;
  public static final int PRODUCT = 38;
  public static final int ARRAY = 6;
  public static final int MINUS = 36;
  public static final int FOR = 11;
  public static final int GREATER_THAN = 43;
  public static final int READ_LN = 63;
  public static final int NOT = 15;
  public static final int SEMICOLON = 30;
  public static final int AND = 5;
  public static final int RECORD = 19;
  public static final int TYPE = 61;
  public static final int NIL = 14;
  public static final int IN = 50;
  public static final int OR = 17;
  public static final int COMMA = 32;
  public static final int WRITE_LN = 62;
  public static final int DIV = 8;
  public static final int BEGIN = 3;
  public static final int UNTIL = 58;
  public static final int LESS_EQUAL = 46;
  public static final int PLUS = 35;
  public static final int GREATER_EQUALS = 45;
  public static final int QUOTE = 25;
  public static final int IF = 13;
  public static final int ID = 49;
  public static final int DOT = 33;
  public static final int OF = 16;
  public static final int BOOLEAN = 64;
  public static final int EOF = 0;
  public static final int TRUE = 66;
  public static final int INT_CONST = 65;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MOD = 40;
  public static final int RIGHT_PAR = 27;
  public static final int COLON = 31;
  public static final int CHAR_CONS = 68;
  public static final int ELSE = 10;
  public static final int FILE = 53;
  public static final int TO = 21;
  public static final int WHILE = 24;
  public static final int THEN = 20;
  public static final int ASIGN = 34;
  public static final int END = 4;
  public static final int RIGHT_KEY = 69;
  public static final int STRING = 51;
  public static final int DOWNTO = 22;
  public static final int FALSE = 67;
  public static final int LEFT_PAR = 26;
  public static final int LESS_THAN = 44;
  public static final int LEFT_BRACKET = 28;
  public static final int VAR = 23;
  public static final int PROCEDURE = 18;
  public static final int DO = 9;
  public static final int SET = 52;
}

