
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 14 09:15:44 CST 2017
//----------------------------------------------------

package pascal.compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RIGHT_KEY = 11;
  public static final int SEMICOLON = 12;
  public static final int END = 5;
  public static final int WRITE_LN = 4;
  public static final int ASIGN = 16;
  public static final int COLON = 13;
  public static final int PROGRAM = 2;
  public static final int BEGIN = 3;
  public static final int LEFT_PAR = 6;
  public static final int COMA = 14;
  public static final int EOF = 0;
  public static final int RIGHT_PAR = 7;
  public static final int LEFT_BRACKET = 8;
  public static final int error = 1;
  public static final int DOT = 15;
  public static final int ENTERO = 17;
  public static final int LEFT_KEY = 10;
  public static final int RIGHT_BRACKET = 9;
}

